### ISSUE TITLE
Enhancement: Token Flipping with Rotating Arrows.

### ISSUE THREAD

**Issue by simulacrum-1** [mclemente/about-face#11]
One final idea is the ability flip the token image either left or right while the token is locked. And have the Arrows rotating.
So the character Faces Left when heading left or Faces Right when heading right.
This would have to be activated on a token/actor by token/actor basis as you have to know which way the art is facing. I guess you would probably, just use it for PCs. This is just icing on the cake, as it works great without this feature.

**Comment by mclemente** [comment]
Have you checked the settings? You can already make it so it only flips horizontally or vertically.

**Comment by simulacrum-1** [comment]
It all goes a bit crazy.

**Comment by simulacrum-1** [comment]
Here's a video of what happens. Too big to upload it here I'm afraid.
https://www.dropbox.com/t/Vlzh3sRG4e17Omgd

**Comment by simulacrum-1** [comment]
Seems locking rotation also locks flipping.

**Comment by mclemente** [comment]
Yes, Lock Rotation locks every kind of rotation (flipping is a kind of rotation).
Update the module and check the new stuff, it might do what you're looking for.

**Comment by simulacrum-1** [comment]
Flipping Vertical flip Vertical. Flipping Horizontal also flips vertical.

**Comment by simulacrum-1** [comment]
Also If you have Flipping on you can't rotate the arrows.

**Comment by simulacrum-1** [comment]
Also locking rotation doesn't seem to work. Sorry :(

https://user-images.githubusercontent.com/68729767/135724999-6e312f5d-f6a3-4d11-ac67-607e42029df7.mp4

**Comment by simulacrum-1** [comment]
> Yes, Lock Rotation locks every kind of rotation (flipping is a kind of rotation).
I may have found a solution. Mirroring.

https://user-images.githubusercontent.com/68729767/135725843-f1226cef-cf39-43c7-8c3a-5748b1101637.mp4
