### ISSUE TITLE
Unable to install About Face from Foundry 8.9

### ISSUE THREAD

**Issue by Exxar** [mclemente/about-face#14]
Hello, when attempting to install About Face from within Foundry, the version 3.7 is listed as the current version, but when I attempt to install it I get the error message message "Installation failed: About Face module version 3.8 requires a more modern Foundry VTT core version of 9.2 or greater"

![image](https://user-images.githubusercontent.com/330181/142740665-335d643d-8cd6-4842-85da-f6f4f6e31fee.png)

**Comment by mclemente** [comment]
Sorry, I didn't update the .json link to 3.7 properly when I set up 3.8 on the package's page. It should be fixed now.

**Comment by Exxar** [comment]
No problem, I just wanted to bring this to your attention, I installed the module using the manifest from releases here.
