### ISSUE TITLE
custom indicator

### ISSUE THREAD

**Issue by Orionox** [mclemente/about-face#17]
Basically, I think it could be cool if we could define our own custom indicators, basically, I want an indicator that looks like this because I enforce facing for attacks of opportunity and I think it would be cool to have the indictor basically Highlight the area they can be performed in. As you can see in the picture attached, there is a red highlight around the character representing their Attack of opportunity area. 

![Capture](https://user-images.githubusercontent.com/20059838/144747382-58858976-84c0-4e19-90c2-3d093f284322.PNG)

**Comment by VatroKeilger** [comment]
Actually I was wondering the same thing, if I could make a PNG directional overlay to appear when hovering over the token to indicate facing zones, like front side and rear.

**Comment by mclemente** [comment]
I'm closing this issue because this won't be implemented due to its complexity, I'm sorry.
