### ISSUE TITLE
Error in Legacy World

### ISSUE THREAD

**Issue by Naroek56** [mclemente/about-face#24]
Hi everyone,

Win10, Foundry 9 - 242, About Face 3.10.1

I have encountered an issue with an old world. When trying to use the horizontal flip on a token I get the following error message:

> logic.js:184 About Face: failed to mirror token "tech" (ID: JZuK6SvOcZYxnM49).
> 			tokenDocument.flags.about-face.facingDirection: right
> 			canvas.grid.type: 0
> 			flipOrRotate: flip-h
> 			facingDirection: right
> 			angles: undefined
> 			TypeError: Cannot read properties of undefined (reading 'right')

No other modules are activated. This error does not occur in a new world. I have put a lot of work into it and except for this everything is working. Do you know how I could fix this?

Thanks in advance!

**Comment by mclemente** [comment]
You're playing on a gridless map, right? Does it happen with Square grid?

**Comment by Naroek56** [comment]
Oh, you're right, it only seems to work on square maps. On gridless it breaks and on hex it defaults back to global settings. Why is that?

**Comment by mclemente** [comment]
1) It was designed assuming nobody would use gridless. I guess it could use Square's implementation.
2) It isn't using defaults, it's just that it's some old code that I haven't tested it fully since I assumed it would work fine and it seems the angles are being calculated differently on V9.

**Comment by Naroek56** [comment]
1. That would be much appreciated, since I like working with Hex and Gridless.
2. I mean when I have global "rotate" and change the token setting on hex to "flip horizontal", it changes back to "global", so rotate, as soon as I move.

**Comment by mclemente** [comment]
Hm, it might be just not saving instead of reverting. It sometimes it saves correctly, so I guess it's a race condition somewhere in the way.

As for the Facing rules, I've got a way saner logic now.
