### ISSUE TITLE
support step back without changing face

### ISSUE THREAD

**Issue by josmardias** [mclemente/about-face#25]
I would like to use this module but not being able to skip the change direction is kind of painful.

My table use vision angle 180º and move points rules, so being able to step back without changing facing is important for us. With the "auto face change" of this module the token vision would reveal enemy positioning on it's back.

So for this I have these ideas (I prefer `2)`):

1) Detect step back and not change the token face
For both square and hex boards, there is a position that is 180º from the current face.
In this case just make the movement without changing the token face.
Make this configurable for backwards compatibility.

2) Detect step back and sideways
Same as 1) but also detect a sideways movement.
For a square board it's more simple bc there is only step back and sideways, on both cases just don't change token face.
For a hex board is a bit more complicated. Here's how GURPS solve it:
![image](https://user-images.githubusercontent.com/413430/151226380-19673176-0ec4-4c2c-b1cf-78e11b1ce6d3.png)
In this case I would say back/left/right shouldn't change face.

3) Suport a hot key to disable change face for that movement

**Comment by mclemente** [comment]
Update and check out the new Step Back setting, it's an implementation of Idea 1. Idea 2 is obviously the best choice, but I need more time to test it out since I need to take into account two other spaces instead of just the last position.

**Comment by josmardias** [comment]
Thanks for the quick reply.

So, I just tested the Step Back setting and it's not accurate to my description of 1).
The Step Back setting is not exactly what I'm expecting. It works for most cases, but not for the general case.

Here's a step by step of what the module is doing:

- Started looking north-east
![image](https://user-images.githubusercontent.com/413430/151444147-0a634e36-cd4d-4dde-86e8-0e42623220a8.png)
- One step forward, the module properly change face with movement direction
![image](https://user-images.githubusercontent.com/413430/151444476-ed49e657-4ead-4485-afbe-68ecca60c7e2.png)
- Moved to east, the module properly change with movement
- I manually change face to the south west, because that's something I can do
![image](https://user-images.githubusercontent.com/413430/151444486-ac0a0893-0523-408a-9b23-88f5a3528357.png)
- One step to west. The module didn't change face with the movement, vecause it's relying on "last position"
![image](https://user-images.githubusercontent.com/413430/151444493-1aa431eb-a9c1-4daf-bc5d-730217ff2aaf.png)

My expectation was to keep face if and only if the movement is 180º with the current face, doesn't matter the last position.

I can take a look at the code if that's something you're ok with the current state of Step Back.
I tried it before but it was on the previous repo (eadorin/about-face), it took me some time to figure I was not looking at the right one.

**Comment by mclemente** [comment]
This was one the issues with the implementation. If you're going to use SHIFT + direction key, you might as well use it again when moving back into the last position.

The problem with figuring out the 3 squares/hexes behind is that the logic is different for Squares, Hex Rows and Hex Columns. 
Squares is obviously the easiest, but there's no point implementing that feature just for one grid type.

If you figure out how do to it on Hex Rows I can make it work for squares and columns. 

Some help:
- For Rows, X size = `canvas.dimensions.size`, Y size = `Math.sqrt(3) * 0.5 * canvas.dimensions.size`.
- You might need to look at Foundry.js around the `HexagonalGrid` class.

**Comment by josmardias** [comment]
I'll take a look into it.

Btw, I don't think we need to figure out the 3 hexes behind, just 1.

At least for GURPS there is one 1 real behind, the other 2 are considered left and right (take a look at the image I posted previously).

**Comment by josmardias** [comment]
Actually I think we need more input on this.

I can see it working on my table (just back, not left and right), but I wonder how other people playing on hex board feel about this.

**Comment by josmardias** [comment]
So, I talked to some friends. They said: it's better to simplify and just have a hot key to enable face change for that movement only.

In other words, a movement would never change face. A movement holding SHIFT would always change face.

This makes sense to me, and we don't need to calculate Front/Left/Right/Back anymore

**Comment by josmardias** [comment]
Just opened PR #26 that adds a setting to make auto rotation opt in per movement.
That's enough for my table. I hope it works for you and the rest of the community :smile:

I already have it on my local install and I'll start using in my next session (8 hours from now).

Thanks @mclemente, we can move the discussion to that PR if there is something else in your mind.

**Comment by josmardias** [comment]
I'm reopening this issue because the current implementation doesn't match any of the suggested options.

**Comment by mclemente** [comment]
> In other words, a movement would never change face. A movement holding SHIFT would always change face.

You have found out the modifier keys don't work at all. It was the first solution I've tried and this issue would've been resolved on the same day.

>Just opened PR #26 that adds a setting to make auto rotation opt in per movement.

Your PR would make it so there were two settings for a single feature. Even if I removed the Step Back setting and left yours, it would be hard-coded to Z, which would clash with the AZERTY layout and wouldn't be good for the QWERTZ layout either.

Also, there might be games where disabling the rotation entirely is just as important as disabling it for a single movement. And for that, Z isn't a good key to be held while pressing WASD.

>I'm reopening this issue because the current implementation doesn't match any of the suggested options.

The setting was removed in favor of the Toggle Token Rotation keybinding, which serves the same purpose and gives more control to users when to not rotate their tokens.

**Comment by josmardias** [comment]
We need a feedback on screen to know the current toggle state.
That's one of the main pain points on the current implementation.

**Comment by mclemente** [comment]
You get a [notification](https://github.com/mclemente/about-face/blob/master/about-face.js#L24) when you toggle it.

Your players aren't seeing this?
![image](https://user-images.githubusercontent.com/5288872/151707857-18de8e22-8970-41a8-b8e8-d6cb3dc4f8fb.png)

Also, I'm fixing the tooltip so both say "Rotation".

**Comment by josmardias** [comment]
Hum, maybe they were complaining about not knowing the current state _without_ pressing it.
But if there is this notification I think it's ok.

Btw I'm not using this feature anymore, I'm playing with my local install reverted to my changes from that PR.
My players prefer to either use "z" + mouse drag for auto rotation or SHIFT scroll + WASD for manual.
