### ISSUE TITLE
Tokens travel past their destination and snap back with Drag Ruler

### ISSUE THREAD

**Issue by tprussak** [mclemente/about-face#3]
When I drag a token on a movement that causes it to rotate, it will visually teleport to the destination, and continue to animate forwards for usually about 2/3 of the original movement distance. This will potentially reveal areas past walls if vision on movement is enabled. After the animation finishes, the token will snap back to the proper location. 

I have isolated this issue to occur with just Drag Ruler and About Face, and only when a token is dragged in a way that causes its orientation to change.

**Comment by mclemente** [comment]
Yes, it seems About Face and Drag Ruler are trying to update the token at the same time and that's the result of it.

**Comment by mclemente** [comment]
This should be fixed with the 3.0 version now.
