### ISSUE TITLE
Prototype Token Settings don't save

### ISSUE THREAD

**Issue by LordoftheMorning** [mclemente/about-face#30]
My global settings are to flip horizontally only, but when I attempt to edit a specific prototype token (in this case, my party's keelboat) to set it to rotate, it does not remember the change. After I click the update button on the prototype token, when I open the prototype token interface back up, the setting have reverted back to global. The result is that I have to set the desired behavior every time I put the token in a scene.

**Comment by Scaenicus** [comment]
For me it saves, but only until I reopen "Prototype token", then my settings are lost again (even if I don't go to the "About Face" tab, but change something different).
