### ISSUE TITLE
Feature request: Compatibility with Stairways

### ISSUE THREAD

**Issue by lucaspicerni** [mclemente/about-face#34]
When used in conjunction with the [Stairways](https://gitlab.com/SWW13/foundryvtt-stairways) module, About Face results in strange behavior of tokens after teleporting, such as the token face and the AF indicator pointing in different directions.

![image](https://user-images.githubusercontent.com/95550238/166395507-63d7478f-4677-40e8-a3c9-818ecefbdc4d.png)

The face of the token is stuck in the wrong direction after this.

**Comment by mclemente** [comment]
Hello, it's been a while. Could you try this interaction again on the latest version (3.17)?

That behavior might have been caused by the token's flags being overwritten when it was being teleported.

**Comment by lucaspicerni** [comment]
It's corrected! Thank you for your work.
