### ISSUE TITLE
Feature Request: Turn with SHIFT + NUMPAD

### ISSUE THREAD

**Issue by 2ndNegative** [mclemente/about-face#35]
While SHIFT + WASD works perfect in square based grids, It does not work well in hex based grids (even facing between the hexes at points). This could be very easily solved by adding a keybind to turn without moving using SHIFT + NUMPAD. You already CAN move using the numpad, and the facing there works correctly, you just cannot do it without moving.

**Comment by mclemente** [comment]
I haven't changed anything, but testing on V10 seems to work just as you described.
