### ISSUE TITLE
Arrows...

### ISSUE THREAD

**Issue by pemerson71** [mclemente/about-face#37]
On two of my tokens, one of which is only a couple weeks old and the other I replaced about ten minutes ago, the direction indicator arrow doesn't show, regardless of Visibility State, unless I'm on mouseover with them.  I've checked all the settings I know about and have been unable to fix the issue.  To clarify, one of these tokens has been added fresh since About Face was put in its own Token Configuration tab, and the other has been replaced, today, and neither shows the direction indicator arrow.  The one added a couple weeks ago fell under my default token configuration, and I've put on many other tokens since then which do not display this problem.

Thank you for any time you're able to spare.

**Comment by mclemente** [comment]
Could you zip that world's folder and send it to me so I can take a look?

**Comment by pemerson71** [comment]
Just here?  Or, do you have an email or Discord you'd prefer to have it on?

I'll be a little while getting back to you, unless it's just before I leave for Lunch with my Wife.

**Comment by mclemente** [comment]
It can be through Github, just drag & drop the zip file here.

**Comment by pemerson71** [comment]
[ForgeVTT-export-torgtest-2022-07-11_16_37_4.zip](https://github.com/mclemente/about-face/files/9088737/ForgeVTT-export-torgtest-2022-07-11_16_37_4.zip)

I hope this helps.

**Comment by mclemente** [comment]
I assume they're the two characters in the Dreamtime scene.

Jacques and Chesse don't have player owners, so they're treated as NPCs, and your NPC settings are set to Hover.

**Comment by pemerson71** [comment]
Ahh, okay.  That would do it, I guess.  Is there another setting that allows me to turn that 'feature' on or off, somewhere?  I would like to see arrows on ALL my Characters, regardless.  If there's a token on the board, I want it to have an arrow; is that possible?  Please?

Thank you for looking over this; I'm grateful that you would take the time to do so, since it's not a small world, anymore, hehe.

**Comment by mclemente** [comment]
You're welcome, it's hard to replicate some issues sometimes, so getting into users' worlds is faster.

There's two settings: `(NPCs) Enable token indicators` and `(PCs) Enable token indicators`. Your NPC setting is set to On Hover, so you just need to change it to Always on the module's settings.

If that's all, I will be closing this issue.
