### ISSUE TITLE
[feature] more control over pointer

### ISSUE THREAD

**Issue by Mechanized82** [mclemente/about-face#38]
Is it possible to create more control over the pointer other than moving?  If I move west but attack north, my pointer is west... kinda weird.  I can move down then up, but that's just extra steps. 

Perhaps since so many toggle keys are already used for something else in foundry, create an entry in settings that lets players customize their toggle key and that toggle key plus arrows moves the pointer and not the token.  Or better yet a toggle key that just lets the player click on their target to move the pointer in that direction.

**Comment by mclemente** [comment]
For systems where facing and movement are separate things I suggest using either the "Lock Indicator Rotation" setting or the "Toggle Token Rotation" keybinding.

**Comment by Mechanized82** [comment]
Sorry about that,  works great!  Thanks!
