### ISSUE TITLE
Error When saving settings

### ISSUE THREAD

**Issue by Snailramp** [mclemente/about-face#4]
With about face enabled, the Save Settings button on the main config page does nothing, throws this error:

![image](https://user-images.githubusercontent.com/85088198/132091213-1a56c1b4-1dda-489c-90d7-4096f8f63a56.png)

Thank you for your time.

**Comment by SR5060** [comment]
This also happens when tokens are hovered on: 
![image](https://user-images.githubusercontent.com/85184490/134722677-a79ca428-fe4f-4ead-8b90-4678cdc03c53.png)

**Comment by mclemente** [comment]
Fixed on the 3.0 release.
