### ISSUE TITLE
Version 3.18 Compatibility not correctly labelled

### ISSUE THREAD

**Issue by Lan2660** [mclemente/about-face#40]
Hi,

I believe version 3.18 has its compatibility labelled as being compatible with version 9 however when installed it does not show up in the modules list and does not function correctly. This is causing issues on the forge as the module is updated and there is no warning or compatibility issue, but the module stops showing up and stops functioning. The only way to back date the module is to install 3.17 manually through the json.

I hope that explains the issue, thank you.

**Comment by mclemente** [comment]
I missed updating the minimum compatibility to 10, I'm sorry.
It should be fixed now. Forge API should take up to 5 minutes to update the listing on its site (if it does anything, I'm not sure how it diferentiates from V9 to V10), but it should stop updating to 3.18 on V9 games.

**Comment by Lan2660** [comment]
No problem! I managed to fix it but I thought I should let you know in case it causes issues for other users. Thanks for fixing it so quickly.
