### ISSUE TITLE
V10 - 288 - Tokens won't rotate / mirror without moving

### ISSUE THREAD

**Issue by Wiggledude** [mclemente/about-face#48]
Unfortunately holding SHIFT + Arrow Keys / WASD won't work for me here.
Running V10 Foundry on the latest 288 hotfix.
The tokens still mirror correctly when taking a move on the grid, but won't rotate on the same spot.
Any issue known here?

**Comment by mclemente** [comment]
Does this happen on a brand new world? Does the indicator move correctly? All other modules disabled? What system are you on? Any errors on the console?

**Comment by mclemente** [comment]
SHIFT + Keys rotates the token on Core Foundry. This module doesn't change that behavior.
If you want the token to not rotate, you need to lock its rotation. You need to toggle the `Lock Rotation` setting.
For scenes with tokens already placed, you need to go to the scene's setting -> About Face -> toggle the `Lock Rotation` checkbox (it it isn't toggled already) -> Apply to existing tokens.
