### ISSUE TITLE
Token's facing direction

### ISSUE THREAD

**Issue by Lertuga** [mclemente/about-face#49]
I use round tokens and I am having issues with facing directions and mirroring.
 
If I set "global facing direction: left", each token with their image facing left will mirror correctly. However, each token with image facing right, no matter if I set the specific token's facing direction left or right, it always mirror the wrong way (when it move to the right it will mirror facing the left etc).

If I set "global facing direction: right", it happens the same but, in this case, the tokens which mirror the wrong way are the ones with images facing left.

Are there any problems with the option to set individual facing direction on specific token? Or am I making some mistake?

PS: I tried mirroring, directly on the token image settings, but nothing change.

I'll try to upload a brief video of the issue I'm talking about and the settings:

https://user-images.githubusercontent.com/102749221/198413298-0ceb7fbc-6be7-4727-9ad9-9791fbb09ff2.mp4

![unknown](https://user-images.githubusercontent.com/102749221/198413315-caecb035-8634-4462-b8dc-edfb2fcc1ab8.png)

Thanks

**Comment by mclemente** [comment]
The logic was looking at the `Mirror or Rotate Token` token setting being set to `global` instead of the `Facing Direction` token setting.
It will be fixed on the next release.
