### ISSUE TITLE
Global toggle for facing indicators

### ISSUE THREAD

**Issue by janmarcano** [mclemente/about-face#5]
I'm using About Face to handle token flipping automatically, however managing the facing is not something I need on my campaign. I can disable it in the module settings, but only for myself; so then every player will still have the facing indicator unless they go and turn if off.

I'd like to be able to turn off the facing indicators globally without requiring my players to go through the settings.

**Comment by mclemente** [comment]
I suggest you use the [Force Client Settings](https://foundryvtt.com/packages/force-client-settings) module whenever you need to turn a client setting into a global one.

**Comment by janmarcano** [comment]
This is really useful, thank you so much!
