### ISSUE TITLE
Suggestion : Move Backwards

### ISSUE THREAD

**Issue by R0TEAM** [mclemente/about-face#53]
Option (over an key) to move the token back, but dont change his face direction ...

**Comment by mclemente** [comment]
>Option (over an key)

Do you mean you want a setting for that instead of the Toggle Token Rotation keybind or do you want a setting that makes the token to not change its indicator if it moves back to its last position?

**Comment by R0TEAM** [comment]
have just tested the Token Rotation keybinding ... its dont work at all ...
If i press the key .. it says " Token Rotation ON" - and it should off ...
It is something like "off", as if i move the token, the token indicator stay on the position (dont rotate) - butthe token self rotate one time in face south and then stay at this facing by moving ...
So - yes it freezes the Token indicator (but only this) , and it freezes the Token self in an south facing state, but dont freeze the initial state of the token .. and if i rotate the token after moving, it rotates from the south facing .... 
If i press the key again, it say "Token Rotation OFF" .. and it is then back to default, rotate the token with the movement ....

**Comment by mclemente** [comment]
I still don't know what you want. Your suggestion isn't clear.

**Comment by R0TEAM** [comment]
mhh . sorry, english is not my first language .... il try again ....
first, sorry, have not remembered that is an key already available to disable rotation of token by movement of it ...
so the suggestion is obsolete - it is already an key for this available ... sorry again ...
second, i have then tested the key, and it worked not really (as i have writen)
so in the end it is more like an bug report as an suggestion ;)
