### ISSUE TITLE
Copyed Tokens cant rotate properly (again)

### ISSUE THREAD

**Issue by R0TEAM** [mclemente/about-face#59]
This was an probleme an short time ago ...
If you copy/paste an token - he get "mad" at rotating him ... show in wrong direction,jump big arcs and simply cant controled sensefull (the rotation).
Now this bug is back ....
If i drag an token on the canvas all is working fine .. if i copy-paste it from the canvas then the rotation control is broken ...

**Comment by mclemente** [comment]
Hey, thanks for the report! It should be fixed now on v3.22.4.
I'm not sure what you meant by "jump big arcs", though. The only time I notice something similar is when I'm trying to debug the module and a breakpoint is triggered during a movement.
