### ISSUE TITLE
When Copy/Pasting tokens from one map to another, it adds a Rotation Offset that screws up their rotation

### ISSUE THREAD

**Issue by GambetTV** [mclemente/about-face#62]
Weird bug I'm running into. By default I have "Facing Direction" set to Down, and Rotation Offset set to 0. However, if a token is facing to the left when I copy/paste it to another map, it will paste with the token facing left, which is good, but for some reason it will change its Rotation Offset in the Token Configuration to 90, which from that point on means if I move the token to the right, it will be facing down instead of to the right, if I move it up it'll face the right, etc. I don't know why it adds the Rotation Offset, but it definitely shouldn't be happening.

**Comment by mclemente** [comment]
Are you on the latest version? That issue was fixed on v3.22.4.

**Comment by GambetTV** [comment]
I'm on v3.22.5 and it's still happening.

**Comment by mclemente** [comment]
Does this error persists? Was this somehow related to other modules, like #63?

**Comment by GambetTV** [comment]
I couldn't tell you if it's caused by another module, as it happens so inconsistently and only happens when you copy a token from one map to another, that it'd just be really long and complicated to test it out to any reasonable certainty. That said, it happened to me as recently as a few hours ago, after I updated the module to the 3.22.6. But only to one token, which seems pretty good compared to how it used to be where I'd copy 7 tokens and 4 of them would be messed up.
