### ISSUE TITLE
Bug with Multilevel Tokens Module

### ISSUE THREAD

**Issue by GambetTV** [mclemente/about-face#65]
With your module enabled and none others aside from Multilevel tokens, having a character move onto a teleporter which should instantly teleport them from one spot to another on the same scene causes the token to actually move across the map to the new spot, moving through walls and basically seeing a lot of unwanted stuff in the process. Disabling your module fixes the issue, and tokens will then teleport across the map instantly.

**Comment by mclemente** [comment]
Sorry for that. It should be fixed now on the latest version.
