### ISSUE TITLE
Please add an option not to mirror or rotate the token

### ISSUE THREAD

**Issue by TogaParty** [mclemente/about-face#66]
This breaks token with legible text on them, it flips backwards or rotates it and it's illegible.  Disabling the pointer doesn't resolve this.

**Comment by mclemente** [comment]
This is already a feature. Just toggle the Lock Rotation in the token configs for each token or toggle the Lock Rotation in the module's settings to affect tokens globally.
![image](https://user-images.githubusercontent.com/5288872/208485437-8f242a5d-19b8-41dc-b392-63707fd5d3a5.png)
![image](https://user-images.githubusercontent.com/5288872/208485525-85809c0f-adf6-4f5f-b563-0d68fce87986.png)
