### ISSUE TITLE
Vision not follow indicator unless token set to rotate.

### ISSUE THREAD

**Issue by Grandsome** [mclemente/about-face#68]
Vision not follow indicator unless token set to rotate in about face settings.
Is this the intended behaviour? 
I'd like to lock the token image but have the vision follow the indicator.

**Comment by mclemente** [comment]
That's the intended behavior, as in, it isn't bugged, but I can see your point and will add a better interaction for that.

**Comment by mclemente** [comment]
Should be fixed on the latest version (3.22.9).

**Comment by Grandsome** [comment]
Awesome!
