### ISSUE TITLE
Bunch of errors on v11. Arrows don't appear anymore.

### ISSUE THREAD

**Issue by wonderfulnewworld** [mclemente/about-face#77]
Been getting it on version 11. The arrows don't appear.

![image](https://github.com/mclemente/about-face/assets/99152399/994c3e2e-7812-492b-8261-0ae366df8915)
![image](https://github.com/mclemente/about-face/assets/99152399/cf45a53e-eab1-46c8-b693-21904fc93bd6)

**Comment by mclemente** [comment]
Disale the Disable Animations setting in the meantime until I work on a fix. Sorry for your troubles.

**Comment by wonderfulnewworld** [comment]
So the errors don't appear now, but now the arrows only appear when I drag a token onto the canvas for the first time, and never again. @mclemente

**Comment by mclemente** [comment]
Do you mean they don't show up when refreshing the page?

**Comment by wonderfulnewworld** [comment]
Yup, don't show up at all. If I move the token after dragging it out, the arrows are gone. Tokens placed before don't show it either.

**Comment by mclemente** [comment]
I am clueless here, latest changes were really small. Try reinstalling the module.

**Comment by wonderfulnewworld** [comment]
Alright so I experimented a bit more, it seems what's actually broken is "Show on Hover." If I force it to always show, then it shows, but on hover it doesn't.

**Comment by wonderfulnewworld** [comment]
![image](https://github.com/mclemente/about-face/assets/99152399/6c5a75f3-c4b1-4cb4-8d39-24da9f29cec7)
I also got this error when I tried to disable the direction indicator per token, and the token actually disappeared. Although maybe it's a different module.

**Comment by wonderfulnewworld** [comment]
Seems to happen when I press Apply on the token period.

**Comment by mclemente** [comment]
Should be fixed now.

**Comment by mclemente** [comment]
> Seems to happen when I press Apply on the token period.

If you're editing a token and apply any change, that's default Foundry of redrawing the token.
