### ISSUE TITLE
Feature Request: Add back in Animation Disabling

### ISSUE THREAD

**Issue by GambetTV** [mclemente/about-face#78]
I saw your patch notes say that you disabled it because the animation is no longer super slow, but I am not sure of that. When simply rotating the token without moving it, it is true that the animation is much speedier. However, when using your module and dragging the token across some distance, it seems to be acting exactly the same for me as it did for v10. If I drag a left-facing token to the right 50 squares, it will take all 50 squares to fully rotate 180 degrees. If you're not seeing the same thing, is that because you have another module/setting, or are you defining the animation not moving super slow in another way?

If not, and if it's not too much trouble, could you add the animation disabling back in? Fast or slow, personally I just don't like how it looks, how it always angles the rotation towards the top of the screen, it just feels unnatural to me.

**Comment by mclemente** [comment]
The method that was being overriden (_animateFrame) became private on V11, so I can't just replace it with my function that skipped only the rotation/mirroring animations based on the setting.
To skip the rotation/mirroring animation on V11 it would skip the entire animation.

**Comment by GambetTV** [comment]
I don't suppose you could look into this again? I heard that one of the recent updates took a bunch of stuff out of private, and I'm wondering if this might be one of them. I say that because v11 broke another module I use, which changed token images and allowed the new token to have a different scale to it, but it would weirdly animate the scaling up/down of the image. Anyway long story short I asked the modulemaker (the module is Token Variant Art) if he could patch that out, and he was able to do so, and now the tokens are able to swap instantly without any animation.

My hope is that if he was able to do so, then maybe you'd be able to do so as well! If not, totally understandable. I apologize that I keep coming back around to it, but your module is amazing, and IMO it's kind if ruined by the really crappy animation Foundry's forcing on us. Dragging a token 50 feet and watching it do the slowest 180 from point A to point B just looks silly, and it's really keeping me from updating, haha.

**Comment by mclemente** [comment]
Still not possible. TVA does it the usual way, skipping the whole animation, since there is just a single animation when changing scale.

**Comment by GambetTV** [comment]
Bummer, but thank you for looking into it!

**Comment by mclemente** [comment]
Animation Disabling will be available again on Foundry V12, this is what an early implementation looks like:

https://github.com/mclemente/about-face/assets/5288872/e17eee02-2867-431b-a180-f1b74b43b7bd

**Comment by GambetTV** [comment]
I appreciate you taking the time to work on this! I understand this is an early implementation, so it may not be up to specs for you yet, which is good! I'd like to suggest a couple changes or additions to make this work more how it did in v9/10.

1. I think it should rotate at the start of movement, not at the end. This will lend itself to much more natural movement for top-down tokens.

2. It should also disable the rotation animation when you're just using Shift + Mousewheel or Ctrl + Mousewheel or Shift + WASD to change your token's facing.

Mostly I'm just looking for the animation to be disabled in a way where the animation is completely gone, with no delay between you making a chance and seeing the new facing.

Appreciate it!
