### ISSUE TITLE
Swap Height and Width When Turning

### ISSUE THREAD

**Issue by Nuku** [mclemente/about-face#8]
Say you have an icon that is 2 high and 1 across, facing down. When it faces left or right, it should be 2 across and 1 high. If it faces up or down, back to 2 high and 1 across.

Is that possible?

**Comment by mclemente** [comment]
It is possible, but it's a bit beyond the scope of this module. I'll try adding a setting that does this once I'm done with updating the module.

**Comment by mclemente** [comment]
Update: this won't be implemented.
