### ISSUE TITLE
Facing indicator not displayed

### ISSUE THREAD

**Issue by UnpardonablyCrassus** [mclemente/about-face#87]
Hi there--I am on Foundry v11.315, using GURPS 0.16.7 and an array of other modules. About Face stopped drawing the actual indicator on upgrade to Foundry v11. It locks rotation of the token itself and is clearly preserving facing, because with vision limited to an angle, the vision cone rotates appropriately. But I can't get it to draw the indicator arrow itself. Any help would be appreciated!

**Comment by mclemente** [comment]
Are there any errors on the console? And did you update About Face as well?

**Comment by UnpardonablyCrassus** [comment]
About Face is updated to 3.25.3, yep.

No errors in the log, BUT when I unchecked "Hide facing on defeated tokens," all the indicators came back. Marking a token defeated does not remove its facing.

So my immediate problem is solved, but a new (less important) mystery has arisen.
