### ISSUE TITLE
v12 Facing not changing with shift + WASD

### ISSUE THREAD

**Issue by petco130** [mclemente/about-face#93]
As title, migrating from v11 to v12 seems to have borked facing for me. Not sure yet if it's working for new tokens, but for pre-existing tokens, the facing doesn't change mechanically, though the token itself rotates.

**Comment by mclemente** [comment]
Just ported my V11 test world and I couldn't reproduce this. Could you test with just About Face enabled?

**Comment by mikegent01** [comment]
> Just ported my V11 test world and I couldn't reproduce this. Could you test with just About Face enabled?
Here is the error I am having the same issue
Uncaught TypeError: Cannot read properties of undefined (reading 'messageId')
    at logic.js:157:44
    at Array.map (<anonymous>)
    at Polyglot.updateChatMessagesDelayed (logic.js:157:5)
Error: Error thrown in hooked function 'onPreUpdateToken' for hook 'preUpdateToken'. Cannot read properties of undefined (reading '_isReplicatedToken')
    at Hooks.onError (foundry.js:630:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:138:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at #call (foundry.js:612:36)
    at Hooks.call (foundry.js:590:38)
    at #preUpdateDocumentArray (foundry-esm.js:55750:46)
    at async ClientDatabaseBackend._updateDocuments (foundry-esm.js:55701:7)
    at async Function.updateDocuments (foundry-esm.js:11392:23)
    at async TokenLayer.moveMany (foundry.js:34218:5)
onError @ foundry.js:631
await in onError (async)
_updateDocuments @ foundry-esm.js:55701
update @ foundry-esm.js:12255
await in update (async)
updateDocuments @ foundry-esm.js:11392
updateEmbeddedDocuments @ foundry-esm.js:11638
moveMany @ foundry.js:34218
_handleMovement @ foundry.js:1892
(anonymous) @ foundry.js:2009
setTimeout (async)
_onPan @ foundry.js:2009
onDown @ foundry.js:1603
_executeKeybind @ foundry.js:2439
_processKeyboardContext @ foundry.js:2480
_handleKeyboardEvent @ foundry.js:2538
🎁call_wrapped @ libWrapper-wrapper.js:507
_lw_game_keyboard__handleKeyboardEvent @ Bundle.js:127246
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁game.keyboard._handleKeyboardEvent#0 @ libWrapper-wrapper.js:189
(anonymous) @ foundry.js:2152

**Comment by mikegent01** [comment]
![image](https://github.com/mclemente/about-face/assets/70764301/ed40306f-ba4a-49c9-9d3e-32974125adc6)
![image](https://github.com/mclemente/about-face/assets/70764301/ddba769f-250e-4c4f-919a-d950fce1cee4)

**Comment by mclemente** [comment]
Neither of these errors are caused by About Face. Also, disable Multilevel Tokens, it wasn't even verified for V11.

**Comment by mikegent01** [comment]
I am sorry, it seems that this was conflicting with another addon, I have fixed the issue, it was not caused by this addon, find the culprit said it was caused by levels.

**Comment by mikegent01** [comment]
I can confirm the issue is caused by multi level tokens
