### ISSUE TITLE
Scene Configuration has an "About Face" tab with nothing on it.

### ISSUE THREAD

**Issue by GambetTV** [mclemente/about-face#99]
I recall there being options on this tab back in v11, but now there's nothing.

Tested on a fresh world with only libwrapper and About-Face active, on v12.

![image](https://github.com/user-attachments/assets/318f72b3-db23-4ee0-b669-c5b843c13e6b)

**Comment by Sasmira** [comment]
Hello Hello, I have exactly the same problem on scenes from the Star Wars system, but it works correctly on PF2e.
